// message actions
export const MESSAGE = "MESSAGE";

// auth actions
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_ERROR = "LOG_IN_ERROR";

export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_ERROR = "LOG_OUT_ERROR";

// users actions
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

// majors actions
export const LOAD_MAJORS_SUCCESS = "LOAD_MAJORS_SUCCESS";
export const LOAD_MAJORS_ERROR = "LOAD_MAJORS_ERROR";

export const ADD_MAJOR_SUCCESS = "ADD_MAJOR_SUCCESS";
export const ADD_MAJOR_ERROR = "ADD_MAJOR_ERROR";

export const DELETE_MAJOR_SUCCESS = "DELETE_MAJOR_SUCCESS";
export const DELETE_MAJOR_ERROR = "DELETE_MAJOR_ERROR";

// levels actions
export const LOAD_LEVELS_SUCCESS = "LOAD_LEVELS_SUCCESS";
export const LOAD_LEVELS_ERROR = "LOAD_LEVELS_ERROR";

export const ADD_LEVEL_SUCCESS = "ADD_LEVEL_SUCCESS";
export const ADD_LEVEL_ERROR = "ADD_LEVEL_ERROR";

export const DELETE_LEVEL_SUCCESS = "DELETE_LEVEL_SUCCESS";
export const DELETE_LEVEL_ERROR = "DELETE_LEVEL_ERROR";

// faculties actions
export const LOAD_FACULTIES_SUCCESS = "LOAD_FACULTIES_SUCCESS";
export const LOAD_FACULTIES_ERROR = "LOAD_FACULTIES_ERROR";

export const ADD_FACULTY_SUCCESS = "ADD_FACULTY_SUCCESS";
export const ADD_FACULTY_ERROR = "ADD_FACULTY_ERROR";

export const DELETE_FACULTY_SUCCESS = "DELETE_FACULTY_SUCCESS";
export const DELETE_FACULTY_ERROR = "DELETE_FACULTY_ERROR";

// programs actions
export const LOAD_PROGRAMS_SUCCESS = "LOAD_PROGRAMS_SUCCESS";
export const LOAD_PROGRAMS_ERROR = "LOAD_PROGRAMS_ERROR";

export const ADD_PROGRAM_SUCCESS = "ADD_PROGRAM_SUCCESS";
export const ADD_PROGRAM_ERROR = "ADD_PROGRAM_ERROR";

export const DELETE_PROGRAM_SUCCESS = "DELETE_PROGRAM_SUCCESS";
export const DELETE_PROGRAM_ERROR = "DELETE_PROGRAM_ERROR";

// eduPrograms actions
export const LOAD_EDUPROGRAMS_SUCCESS = "LOAD_EDUPROGRAMS_SUCCESS";
export const LOAD_EDUPROGRAMS_ERROR = "LOAD_EDUPROGRAMS_ERROR";

export const ADD_EDUPROGRAM_SUCCESS = "ADD_EDUPROGRAM_SUCCESS";
export const ADD_EDUPROGRAM_ERROR = "ADD_EDUPROGRAM_ERROR";

export const LOAD_EDUPROGRAM_SUCCESS = "LOAD_EDUPROGRAM_SUCCESS";
export const LOAD_EDUPROGRAM_ERROR = "LOAD_EDUPROGRAM_ERROR";

export const SAVE_EDUPROGRAM_SUCCESS = "SAVE_EDUPROGRAM_SUCCESS";
export const SAVE_EDUPROGRAM_ERROR = "SAVE_EDUPROGRAM_ERROR";

// detail eduProgram actions
export const LOAD_DETAIL_EDUPROGRAM_SUCCESS = "LOAD_DETAIL_EDUPROGRAM_SUCCESS";
export const LOAD_DETAIL_EDUPROGRAM_ERROR = "LOAD_DETAIL_EDUPROGRAM_ERROR";

export const SAVE_DETAIL_EDUPROGRAM_SUCCESS = "SAVE_DETAIL_EDUPROGRAM_SUCCESS";
export const SAVE_DETAIL_EDUPROGRAM_ERROR = "SAVE_DETAIL_EDUPROGRAM_ERROR";

export const LOAD_CONTENT_EDUPROGRAM_SUCCESS = "LOAD_CONTENT_EDUPROGRAM_SUCCESS";
export const LOAD_CONTENT_EDUPROGRAM_ERROR = "LOAD_CONTENT_EDUPROGRAM_ERROR";

export const SAVE_CONTENT_EDUPROGRAM_SUCCESS = "SAVE_CONTENT_EDUPROGRAM_SUCCESS";
export const SAVE_CONTENT_EDUPROGRAM_ERROR = "SAVE_CONTENT_EDUPROGRAM_ERROR";

export const LOAD_SCHEDULE_EDUPROGRAM_SUCCESS = "LOAD_SCHEDULE_EDUPROGRAM_SUCCESS";
export const LOAD_SCHEDULE_EDUPROGRAM_ERROR = "LOAD_SCHEDULE_EDUPROGRAM_ERROR";

export const SAVE_SCHEDULE_EDUPROGRAM_SUCCESS = "SAVE_SCHEDULE_EDUPROGRAM_SUCCESS";
export const SAVE_SCHEDULE_EDUPROGRAM_ERROR = "SAVE_SCHEDULE_EDUPROGRAM_ERROR";

export const LOAD_TARGET_EDUPROGRAM_SUCCESS = "LOAD_TARGET_EDUPROGRAM_SUCCESS";
export const LOAD_TARGET_EDUPROGRAM_ERROR = "LOAD_TARGET_EDUPROGRAM_ERROR";

export const SAVE_TARGET_EDUPROGRAM_SUCCESS = "SAVE_TARGET_EDUPROGRAM_SUCCESS";
export const SAVE_TARGET_EDUPROGRAM_ERROR = "SAVE_TARGET_EDUPROGRAM_ERROR";

// subjects actions
export const LOAD_SUBJECTS_SUCCESS = "LOAD_SUBJECTS_SUCCESS";
export const LOAD_SUBJECTS_ERROR = "LOAD_SUBJECTS_ERROR";

export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_ERROR = "ADD_SUBJECT_ERROR";

export const ADD_SUBJECT_BULK_SUCCESS = "ADD_SUBJECT_BULK_SUCCESS";
export const ADD_SUBJECT_BULK_ERROR = "ADD_SUBJECT_BULK_ERROR";

export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_ERROR = "DELETE_SUBJECT_ERROR";

export const LOAD_USING_EDUPRO_SUCCESS = "LOAD_USING_EDUPRO_SUCCESS";
export const LOAD_USING_EDUPRO_ERROR = "LOAD_USING_EDUPRO_ERROR";

// outcomeStandards actions
export const LOAD_OUTCOMESTANDARDS_SUCCESS = "LOAD_OUTCOMESTANDARDS_SUCCESS";
export const LOAD_OUTCOMESTANDARDS_ERROR = "LOAD_OUTCOMESTANDARDS_ERROR";

export const DELETE_OUTCOMESTANDARD_SUCCESS = "DELETE_OUTCOMESTANDARD_SUCCESS";
export const DELETE_OUTCOMESTANDARD_ERROR = "DELETE_OUTCOMESTANDARD_ERROR";

// infoOutcomeStandard actions
export const LOAD_OUTCOMESTANDARD_SUCCESS = "LOAD_OUTCOMESTANDARD_SUCCESS";
export const LOAD_OUTCOMESTANDARD_ERROR = "LOAD_OUTCOMESTANDARD_ERROR";

export const ADD_OUTCOMESTANDARD_SUCCESS = "ADD_OUTCOMESTANDARD_SUCCESS";
export const ADD_OUTCOMESTANDARD_ERROR = "ADD_OUTCOMESTANDARD_ERROR";

// detailOutcomeStandard actions
export const SAVE_DETAIL_OUTCOMESTANDARD_SUCCESS = "SAVE_DETAIL_OUTCOMESTANDARD_SUCCESS";
export const SAVE_DETAIL_OUTCOMESTANDARD_ERROR = "SAVE_DETAIL_OUTCOMESTANDARD_ERROR";

export const LOAD_DETAIL_OUTCOMESTANDARD_SUCCESS = "LOAD_DETAIL_OUTCOMESTANDARD_SUCCESS";
export const LOAD_DETAIL_OUTCOMESTANDARD_ERROR = "LOAD_DETAIL_OUTCOMESTANDARD_ERROR";

// revisions actions
export const LOAD_REVISIONS_SUCCESS = "LOAD_REVISIONS_SUCCESS";
export const LOAD_REVISIONS_ERROR = "LOAD_REVISIONS_ERROR";

export const DELETE_REVISION_SUCCESS = "DELETE_REVISION_SUCCESS";
export const DELETE_REVISION_ERROR = "DELETE_REVISION_ERROR";

// detailRevision actions
export const ADD_DETAIL_REVISION_SUCCESS = "ADD_DETAIL_REVISION_SUCCESS";
export const ADD_DETAIL_REVISION_ERROR = "ADD_DETAIL_REVISION_ERROR";

export const LOAD_DETAIL_REVISION_SUCCESS = "LOAD_DETAIL_REVISION_SUCCESS";
export const LOAD_DETAIL_REVISION_ERROR = "LOAD_DETAIL_REVISION_ERROR";
